version: '3'

services:
  azurite:
      image: 'arafato/azurite:latest'
      hostname: azurite
      ports:
          - '10000:10000'
          - '10001:10001'

  azurite-create-queues:
    image: curlimages/curl:latest
    depends_on:
      - azurite
    hostname: azurite-create-queues
    entrypoint: /bin/sh -c
    command: >
      "
        while ! nc -z azurite 10001; do echo waiting; sleep 3; done;
        curl -X PUT http://azurite:10001/devstoreaccount1/createaccountmessage
        curl -X GET http://azurite:10001/devstoreaccount1?comp=list
        echo 'AZURITE-DONE!'
      "
    extra_hosts:
      - "moby:127.0.0.1"