version: '3.4'

services:
    azurite:
        image: 'arafato/azurite:latest'
        hostname: azurite
        ports:
            - '10000:10000'
            - '10001:10001'

    azurite-create-queues:
        image: curlimages/curl:latest
        depends_on:
            - azurite
        hostname: azurite-create-queues
        entrypoint: /bin/sh -c
        command: >
            "
                while ! nc -z azurite 10001; do echo waiting; sleep 3; done;
                curl -X PUT http://azurite:10001/devstoreaccount1/createaccountmessagequeue
                curl -X GET http://azurite:10001/devstoreaccount1?comp=list
                echo 'AZURITE-DONE!'
            "

    accounts.api:
        image: ${DOCKER_REGISTRY-}accountsapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - MessageQueueOptions__connectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
            - MessageQueueOptions__RequestDelaySeconds=2
        restart: unless-stopped
        ports:
            - "5000:80"
        build:
            context: ../Accounts.Api
            dockerfile: Accounts.Api/Dockerfile
        depends_on:
            - azurite
            - azurite-create-queues
        links: ["azurite", "azurite-create-queues"]
        
    accounts.worker:
        image: ${DOCKER_REGISTRY-}accountsworker
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - MessageQueueOptions__connectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
            - MessageQueueOptions__RequestDelaySeconds=2
        restart: unless-stopped
        ports:
            - "5002:80"
        build:
            context: ../Accounts.Worker
            dockerfile: Accounts.Worker/Dockerfile
        depends_on:
            - azurite
            - azurite-create-queues
        links: ["azurite", "azurite-create-queues"]