version: '3.5'

services:
    rabbitmq:
        image: 'rabbitmq:3-management-alpine'
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=myUserName
            - RABBITMQ_DEFAULT_PASS=myPassword
        ports:
            - '15672:15672'
            - '5672:5672'
        expose:
            - 15672
            - 5672

    rabbitmq-create-queues:
        image: activatedgeek/rabbitmqadmin:latest
        depends_on:
            - rabbitmq
        links: ["rabbitmq"]
        hostname: rabbitmq-create-queues
        entrypoint: /bin/sh -c
        command: >
            "
              while ! nc -z rabbitmq 5672; do echo waiting; sleep 3; done;
              rabbitmqadmin --host rabbitmq -umyUserName -pmyPassword declare exchange name=CreateAccountMessageExchange type=fanout
              rabbitmqadmin --host rabbitmq -umyUserName -pmyPassword declare queue name=CreateAccountMessageQueue durable=false
              rabbitmqadmin --host rabbitmq -umyUserName -pmyPassword declare binding source="CreateAccountMessageExchange" destination="CreateAccountMessageQueue" destination_type="queue"
              rabbitmqadmin --host rabbitmq -umyUserName -pmyPassword list queues
              echo 'RABBIT-DONE!' 
            "
            
    accounts.api:
        image: ${DOCKER_REGISTRY-}accountsapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - MessageQueueOptions__Host=rabbitmq
            - MessageQueueOptions__Port=5672
            - MessageQueueOptions__Username=myUserName
            - MessageQueueOptions__Password=myPassword
        restart: unless-stopped
        ports:
            - "5000:80"
        build:
            context: ../Accounts.Api
            dockerfile: Accounts.Api/Dockerfile
        depends_on:
            - rabbitmq
            - rabbitmq-create-queues
        links: ["rabbitmq", "rabbitmq-create-queues"]

    accounts.worker:
        image: ${DOCKER_REGISTRY-}accountsworker
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - MessageQueueOptions__Host=rabbitmq
            - MessageQueueOptions__Port=5672
            - MessageQueueOptions__Username=myUserName
            - MessageQueueOptions__Password=myPassword
        restart: unless-stopped
        ports:
            - "5002:80"
        build:
            context: ../Accounts.Worker
            dockerfile: Accounts.Worker/Dockerfile
        depends_on:
            - rabbitmq
            - rabbitmq-create-queues
        links: ["rabbitmq", "rabbitmq-create-queues"]
